# Generated by Django 4.2.5 on 2023-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
